/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdljava.x.swig;

public class SDL_Overlay {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_Overlay(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Overlay obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      SWIG_SDLVideoJNI.delete_SDL_Overlay(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setFormat(long format) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_format(swigCPtr, format);
  }

  public long getFormat() {
    return SWIG_SDLVideoJNI.get_SDL_Overlay_format(swigCPtr);
  }

  public void setW(int w) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_w(swigCPtr, w);
  }

  public int getW() {
    return SWIG_SDLVideoJNI.get_SDL_Overlay_w(swigCPtr);
  }

  public void setH(int h) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_h(swigCPtr, h);
  }

  public int getH() {
    return SWIG_SDLVideoJNI.get_SDL_Overlay_h(swigCPtr);
  }

  public void setPlanes(int planes) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_planes(swigCPtr, planes);
  }

  public int getPlanes() {
    return SWIG_SDLVideoJNI.get_SDL_Overlay_planes(swigCPtr);
  }

  public void setPitches(SWIGTYPE_p_unsigned_short pitches) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_pitches(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(pitches));
  }

  public SWIGTYPE_p_unsigned_short getPitches() {
    long cPtr = SWIG_SDLVideoJNI.get_SDL_Overlay_pitches(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setPixels(SWIGTYPE_p_p_unsigned_char pixels) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_pixels(swigCPtr, SWIGTYPE_p_p_unsigned_char.getCPtr(pixels));
  }

  public SWIGTYPE_p_p_unsigned_char getPixels() {
    long cPtr = SWIG_SDLVideoJNI.get_SDL_Overlay_pixels(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_unsigned_char(cPtr, false);
  }

  public void setHwfuncs(SWIGTYPE_p_private_yuvhwfuncs hwfuncs) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_hwfuncs(swigCPtr, SWIGTYPE_p_private_yuvhwfuncs.getCPtr(hwfuncs));
  }

  public SWIGTYPE_p_private_yuvhwfuncs getHwfuncs() {
    long cPtr = SWIG_SDLVideoJNI.get_SDL_Overlay_hwfuncs(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_private_yuvhwfuncs(cPtr, false);
  }

  public void setHwdata(SWIGTYPE_p_private_yuvhwdata hwdata) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_hwdata(swigCPtr, SWIGTYPE_p_private_yuvhwdata.getCPtr(hwdata));
  }

  public SWIGTYPE_p_private_yuvhwdata getHwdata() {
    long cPtr = SWIG_SDLVideoJNI.get_SDL_Overlay_hwdata(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_private_yuvhwdata(cPtr, false);
  }

  public void setHw_overlay(long hw_overlay) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_hw_overlay(swigCPtr, hw_overlay);
  }

  public long getHw_overlay() {
    return SWIG_SDLVideoJNI.get_SDL_Overlay_hw_overlay(swigCPtr);
  }

  public void setUnusedBits(long UnusedBits) {
    SWIG_SDLVideoJNI.set_SDL_Overlay_UnusedBits(swigCPtr, UnusedBits);
  }

  public long getUnusedBits() {
    return SWIG_SDLVideoJNI.get_SDL_Overlay_UnusedBits(swigCPtr);
  }

  public SDL_Overlay() {
    this(SWIG_SDLVideoJNI.new_SDL_Overlay(), true);
  }

}
