/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdljava.x.swig;

public class SDL_Rect {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDL_Rect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Rect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      SWIG_SDLVideoJNI.delete_SDL_Rect(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setX(short x) {
    SWIG_SDLVideoJNI.set_SDL_Rect_x(swigCPtr, x);
  }

  public short getX() {
    return SWIG_SDLVideoJNI.get_SDL_Rect_x(swigCPtr);
  }

  public void setY(short y) {
    SWIG_SDLVideoJNI.set_SDL_Rect_y(swigCPtr, y);
  }

  public short getY() {
    return SWIG_SDLVideoJNI.get_SDL_Rect_y(swigCPtr);
  }

  public void setW(int w) {
    SWIG_SDLVideoJNI.set_SDL_Rect_w(swigCPtr, w);
  }

  public int getW() {
    return SWIG_SDLVideoJNI.get_SDL_Rect_w(swigCPtr);
  }

  public void setH(int h) {
    SWIG_SDLVideoJNI.set_SDL_Rect_h(swigCPtr, h);
  }

  public int getH() {
    return SWIG_SDLVideoJNI.get_SDL_Rect_h(swigCPtr);
  }

  public SDL_Rect() {
    this(SWIG_SDLVideoJNI.new_SDL_Rect(), true);
  }

}
