/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdljava.x.swig;

import java.util.Locale;

class SWIG_SDLMainJNI {

  static {
    try {
      // if set don't loadLibrary ourselves, let client of library do it
      if (System.getProperty("sdljava.bootclasspath") == null) {
	String OS = System.getProperty("os.name", "generic").toLowerCase(Locale.ENGLISH);
	if(OS.indexOf("mac") >= 0 || OS.indexOf("darwin") >= 0) {
		System.load(System.getProperty("user.dir")+ "/" + "libsdljava.so");
	}
	else {
		System.loadLibrary("sdljava");
	}
      }
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native void set_SDL_version_major(long jarg1, short jarg2);
  public final static native short get_SDL_version_major(long jarg1);
  public final static native void set_SDL_version_minor(long jarg1, short jarg2);
  public final static native short get_SDL_version_minor(long jarg1);
  public final static native void set_SDL_version_patch(long jarg1, short jarg2);
  public final static native short get_SDL_version_patch(long jarg1);
  public final static native long new_SDL_version();
  public final static native void delete_SDL_version(long jarg1);
  public final static native int SDL_Init(long jarg1);
  public final static native int SDL_InitSubSystem(long jarg1);
  public final static native void SDL_QuitSubSystem(long jarg1);
  public final static native long SDL_WasInit(long jarg1);
  public final static native void SDL_Quit();
  public final static native long SWIG_SDL_VERSION();
  public final static native String SDL_GetError();
}
