/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdljava.x.swig;

import java.nio.*;
import java.util.Locale;

class SWIG_SDLImageJNI {

  static {
    try {
      // if set don't loadLibrary ourselves, let client of library do it
      if (System.getProperty("sdljava.bootclasspath") == null) {
	String OS = System.getProperty("os.name", "generic").toLowerCase(Locale.ENGLISH);
	if(OS.indexOf("mac") >= 0 || OS.indexOf("darwin") >= 0) {
		System.load(System.getProperty("user.dir")+ "/" + "libsdljava_image.so");
	}
	else {
		System.loadLibrary("sdljava_image");
	}
      }
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native long IMG_Load(String jarg1);
  public final static native long SWIG_IMG_Load_Buffer(Buffer jarg1, int jarg2);
}
