/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.ftgl;

public class FTFont {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FTFont(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FTFont obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected FTFont() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      SWIG_FTGLJNI.delete_FTFont(swigCPtr);
    }
    swigCPtr = 0;
  }

  public boolean attach(String fontFilePath) {
    return SWIG_FTGLJNI.FTFont_Attach__SWIG_0(swigCPtr, fontFilePath);
  }

  public boolean attach(SWIGTYPE_p_unsigned_char pBufferBytes, int bufferSizeInBytes) {
    return SWIG_FTGLJNI.FTFont_Attach__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(pBufferBytes), bufferSizeInBytes);
  }

  public boolean charMap(SWIGTYPE_p_FT_Encoding encoding) {
    return SWIG_FTGLJNI.FTFont_CharMap(swigCPtr, SWIGTYPE_p_FT_Encoding.getCPtr(encoding));
  }

  public long charMapCount() {
    return SWIG_FTGLJNI.FTFont_CharMapCount(swigCPtr);
  }

  public SWIGTYPE_p_FT_Encoding charMapList() {
    long cPtr = SWIG_FTGLJNI.FTFont_CharMapList(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FT_Encoding(cPtr, false);
  }

  public boolean faceSize(long size, long res) {
    return SWIG_FTGLJNI.FTFont_FaceSize__SWIG_0(swigCPtr, size, res);
  }

  public long faceSize() {
    return SWIG_FTGLJNI.FTFont_FaceSize__SWIG_1(swigCPtr);
  }

  public void depth(float depth) {
    SWIG_FTGLJNI.FTFont_Depth(swigCPtr, depth);
  }

  public void useDisplayList(boolean useList) {
    SWIG_FTGLJNI.FTFont_UseDisplayList(swigCPtr, useList);
  }

  public float ascender() {
    return SWIG_FTGLJNI.FTFont_Ascender(swigCPtr);
  }

  public float descender() {
    return SWIG_FTGLJNI.FTFont_Descender(swigCPtr);
  }

  public float lineHeight() {
    return SWIG_FTGLJNI.FTFont_LineHeight(swigCPtr);
  }

  public void bBox(String string, float[] arg1, float[] arg2, float[] arg3, float[] arg4, float[] arg5, float[] arg6) {
    SWIG_FTGLJNI.FTFont_BBox(swigCPtr, string, arg1, arg2, arg3, arg4, arg5, arg6);
  }

  public float advance(SWIGTYPE_p_wchar_t string) {
    return SWIG_FTGLJNI.FTFont_Advance__SWIG_0(swigCPtr, SWIGTYPE_p_wchar_t.getCPtr(string));
  }

  public float advance(String string) {
    return SWIG_FTGLJNI.FTFont_Advance__SWIG_1(swigCPtr, string);
  }

  public void render(String string) {
    SWIG_FTGLJNI.FTFont_Render(swigCPtr, string);
  }

  public int error() {
    return SWIG_FTGLJNI.FTFont_Error(swigCPtr);
  }

    // added during post processing of SWIG generated java files

    public BoundingBox getBoundingBox(String string) {
        float[] llx = {0.0f};
        float[] lly = {0.0f};
        float[] llz = {0.0f};
        float[] urx = {0.0f};
        float[] ury = {0.0f};
        float[] urz = {0.0f};
        
        bBox(string, llx, lly, llz, urx, ury, urz);
        
        return new BoundingBox(llx[0], lly[0], llz[0], urx[0], ury[0], urz[0]);
    }
}