/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.ftgl;

public class FTGLExtrdFont extends FTFont {
  private long swigCPtr;

  protected FTGLExtrdFont(long cPtr, boolean cMemoryOwn) {
    super(SWIG_FTGLJNI.SWIGFTGLExtrdFontUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FTGLExtrdFont obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected FTGLExtrdFont() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      SWIG_FTGLJNI.delete_FTGLExtrdFont(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public FTGLExtrdFont(String fontFilePath) {
    this(SWIG_FTGLJNI.new_FTGLExtrdFont__SWIG_0(fontFilePath), true);
  }

  public FTGLExtrdFont(SWIGTYPE_p_unsigned_char pBufferBytes, int bufferSizeInBytes) {
    this(SWIG_FTGLJNI.new_FTGLExtrdFont__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(pBufferBytes), bufferSizeInBytes), true);
  }

  public void depth(float d) {
    SWIG_FTGLJNI.FTGLExtrdFont_Depth(swigCPtr, d);
  }


}