/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.ftgl;

public class FTGLOutlineFont extends FTFont {
  private long swigCPtr;

  protected FTGLOutlineFont(long cPtr, boolean cMemoryOwn) {
    super(SWIG_FTGLJNI.SWIGFTGLOutlineFontUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FTGLOutlineFont obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected FTGLOutlineFont() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      SWIG_FTGLJNI.delete_FTGLOutlineFont(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public FTGLOutlineFont(String fontFilePath) {
    this(SWIG_FTGLJNI.new_FTGLOutlineFont__SWIG_0(fontFilePath), true);
  }

  public FTGLOutlineFont(SWIGTYPE_p_unsigned_char pBufferBytes, int bufferSizeInBytes) {
    this(SWIG_FTGLJNI.new_FTGLOutlineFont__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(pBufferBytes), bufferSizeInBytes), true);
  }

  public void Render(String string) {
    SWIG_FTGLJNI.FTGLOutlineFont_Render__SWIG_0(swigCPtr, string);
  }

  public void Render(SWIGTYPE_p_wchar_t string) {
    SWIG_FTGLJNI.FTGLOutlineFont_Render__SWIG_1(swigCPtr, SWIGTYPE_p_wchar_t.getCPtr(string));
  }

}
