/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.ftgl;

class SWIG_FTGLJNI {

  static {
    try {
      // if set don't loadLibrary ourselves, let client of library do it
      if (System.getProperty("sdljava.bootclasspath") == null &&
	  System.getProperty("gljava.bootclasspath") == null) {

        System.loadLibrary("ftgljava");
      }
    } catch (UnsatisfiedLinkError e) {
      System.err.println("(ftgljava) Native code library failed to load. \n" + e);
      System.err.println("ftgljava methods will not be available.  Calling them will produce unwanted results.");
    }
  }

  public final static native void delete_FTFont(long jarg1);
  public final static native boolean FTFont_Attach__SWIG_0(long jarg1, String jarg2);
  public final static native boolean FTFont_Attach__SWIG_1(long jarg1, long jarg2, int jarg3);
  public final static native boolean FTFont_CharMap(long jarg1, long jarg2);
  public final static native long FTFont_CharMapCount(long jarg1);
  public final static native long FTFont_CharMapList(long jarg1);
  public final static native boolean FTFont_FaceSize__SWIG_0(long jarg1, long jarg2, long jarg3);
  public final static native long FTFont_FaceSize__SWIG_1(long jarg1);
  public final static native void FTFont_Depth(long jarg1, float jarg2);
  public final static native void FTFont_UseDisplayList(long jarg1, boolean jarg2);
  public final static native float FTFont_Ascender(long jarg1);
  public final static native float FTFont_Descender(long jarg1);
  public final static native float FTFont_LineHeight(long jarg1);
  public final static native void FTFont_BBox(long jarg1, String jarg2, float[] jarg3, float[] jarg4, float[] jarg5, float[] jarg6, float[] jarg7, float[] jarg8);
  public final static native float FTFont_Advance__SWIG_0(long jarg1, long jarg2);
  public final static native float FTFont_Advance__SWIG_1(long jarg1, String jarg2);
  public final static native void FTFont_Render(long jarg1, String jarg2);
  public final static native int FTFont_Error(long jarg1);
  public final static native long new_FTFace__SWIG_0(String jarg1);
  public final static native long new_FTFace__SWIG_1(long jarg1, int jarg2);
  public final static native void delete_FTFace(long jarg1);
  public final static native boolean FTFace_Attach__SWIG_0(long jarg1, String jarg2);
  public final static native boolean FTFace_Attach__SWIG_1(long jarg1, long jarg2, int jarg3);
  public final static native long FTFace_Face(long jarg1);
  public final static native long FTFace_Size(long jarg1, long jarg2, long jarg3);
  public final static native long FTFace_CharMapCount(long jarg1);
  public final static native long FTFace_CharMapList(long jarg1);
  public final static native long FTFace_KernAdvance(long jarg1, long jarg2, long jarg3);
  public final static native long FTFace_Glyph(long jarg1, long jarg2, long jarg3);
  public final static native long FTFace_GlyphCount(long jarg1);
  public final static native int FTFace_Error(long jarg1);
  public final static native long new_FTGLBitmapFont(String jarg1);
  public final static native void delete_FTGLBitmapFont(long jarg1);
  public final static native void FTGLBitmapFont_Render(long jarg1, String jarg2);
  public final static native long new_FTGLExtrdFont__SWIG_0(String jarg1);
  public final static native long new_FTGLExtrdFont__SWIG_1(long jarg1, int jarg2);
  public final static native void delete_FTGLExtrdFont(long jarg1);
  public final static native void FTGLExtrdFont_Depth(long jarg1, float jarg2);
  public final static native long new_FTGLOutlineFont__SWIG_0(String jarg1);
  public final static native long new_FTGLOutlineFont__SWIG_1(long jarg1, int jarg2);
  public final static native void delete_FTGLOutlineFont(long jarg1);
  public final static native void FTGLOutlineFont_Render__SWIG_0(long jarg1, String jarg2);
  public final static native void FTGLOutlineFont_Render__SWIG_1(long jarg1, long jarg2);
  public final static native long new_FTGLPixmapFont__SWIG_0(String jarg1);
  public final static native long new_FTGLPixmapFont__SWIG_1(long jarg1, int jarg2);
  public final static native void delete_FTGLPixmapFont(long jarg1);
  public final static native void FTGLPixmapFont_Render__SWIG_0(long jarg1, String jarg2);
  public final static native void FTGLPixmapFont_Render__SWIG_1(long jarg1, long jarg2);
  public final static native long new_FTGLPolygonFont__SWIG_0(String jarg1);
  public final static native long new_FTGLPolygonFont__SWIG_1(long jarg1, int jarg2);
  public final static native void delete_FTGLPolygonFont(long jarg1);
  public final static native long new_FTGLTextureFont__SWIG_0(String jarg1);
  public final static native long new_FTGLTextureFont__SWIG_1(long jarg1, int jarg2);
  public final static native void delete_FTGLTextureFont(long jarg1);
  public final static native boolean FTGLTextureFont_FaceSize(long jarg1, long jarg2, long jarg3);
  public final static native void FTGLTextureFont_Render__SWIG_0(long jarg1, String jarg2);
  public final static native void FTGLTextureFont_Render__SWIG_1(long jarg1, long jarg2);
  public final static native long SWIGFTGLBitmapFontUpcast(long jarg1);
  public final static native long SWIGFTGLExtrdFontUpcast(long jarg1);
  public final static native long SWIGFTGLOutlineFontUpcast(long jarg1);
  public final static native long SWIGFTGLPixmapFontUpcast(long jarg1);
  public final static native long SWIGFTGLPolygonFontUpcast(long jarg1);
  public final static native long SWIGFTGLTextureFontUpcast(long jarg1);
}
