/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.ftgl;

public class SWIGTYPE_p_class {
  private long swigCPtr;

  protected SWIGTYPE_p_class(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_class() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_class obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

