/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.x.swig;

public class GlewArrays implements GlewArraysConstants {
  public static void glPolygonStipple(short[] mask) {
    GlewArraysJNI.glPolygonStipple(mask);
  }

  public static void glGetPolygonStipple(short[] mask) {
    GlewArraysJNI.glGetPolygonStipple(mask);
  }

  public static void glEdgeFlagv(short[] flag) {
    GlewArraysJNI.glEdgeFlagv(flag);
  }

  public static void glClipPlane(long plane, double[] equation) {
    GlewArraysJNI.glClipPlane(plane, equation);
  }

  public static void glGetClipPlane(long plane, double[] equation) {
    GlewArraysJNI.glGetClipPlane(plane, equation);
  }

  public static void glGetBooleanv(long pname, short[] params) {
    GlewArraysJNI.glGetBooleanv(pname, params);
  }

  public static void glGetDoublev(long pname, double[] params) {
    GlewArraysJNI.glGetDoublev(pname, params);
  }

  public static void glGetFloatv(long pname, float[] params) {
    GlewArraysJNI.glGetFloatv(pname, params);
  }

  public static void glGetIntegerv(long pname, int[] params) {
    GlewArraysJNI.glGetIntegerv(pname, params);
  }

  public static void glLoadMatrixd(double[] m) {
    GlewArraysJNI.glLoadMatrixd(m);
  }

  public static void glLoadMatrixf(float[] m) {
    GlewArraysJNI.glLoadMatrixf(m);
  }

  public static void glMultMatrixd(double[] m) {
    GlewArraysJNI.glMultMatrixd(m);
  }

  public static void glMultMatrixf(float[] m) {
    GlewArraysJNI.glMultMatrixf(m);
  }

  public static void glVertex2dv(double[] v) {
    GlewArraysJNI.glVertex2dv(v);
  }

  public static void glVertex2fv(float[] v) {
    GlewArraysJNI.glVertex2fv(v);
  }

  public static void glVertex2iv(int[] v) {
    GlewArraysJNI.glVertex2iv(v);
  }

  public static void glVertex2sv(short[] v) {
    GlewArraysJNI.glVertex2sv(v);
  }

  public static void glVertex3dv(double[] v) {
    GlewArraysJNI.glVertex3dv(v);
  }

  public static void glVertex3fv(float[] v) {
    GlewArraysJNI.glVertex3fv(v);
  }

  public static void glVertex3iv(int[] v) {
    GlewArraysJNI.glVertex3iv(v);
  }

  public static void glVertex3sv(short[] v) {
    GlewArraysJNI.glVertex3sv(v);
  }

  public static void glVertex4dv(double[] v) {
    GlewArraysJNI.glVertex4dv(v);
  }

  public static void glVertex4fv(float[] v) {
    GlewArraysJNI.glVertex4fv(v);
  }

  public static void glVertex4iv(int[] v) {
    GlewArraysJNI.glVertex4iv(v);
  }

  public static void glVertex4sv(short[] v) {
    GlewArraysJNI.glVertex4sv(v);
  }

  public static void glNormal3bv(byte[] v) {
    GlewArraysJNI.glNormal3bv(v);
  }

  public static void glNormal3dv(double[] v) {
    GlewArraysJNI.glNormal3dv(v);
  }

  public static void glNormal3fv(float[] v) {
    GlewArraysJNI.glNormal3fv(v);
  }

  public static void glNormal3iv(int[] v) {
    GlewArraysJNI.glNormal3iv(v);
  }

  public static void glNormal3sv(short[] v) {
    GlewArraysJNI.glNormal3sv(v);
  }

  public static void glIndexdv(double[] c) {
    GlewArraysJNI.glIndexdv(c);
  }

  public static void glIndexfv(float[] c) {
    GlewArraysJNI.glIndexfv(c);
  }

  public static void glIndexiv(int[] c) {
    GlewArraysJNI.glIndexiv(c);
  }

  public static void glIndexsv(short[] c) {
    GlewArraysJNI.glIndexsv(c);
  }

  public static void glIndexubv(short[] c) {
    GlewArraysJNI.glIndexubv(c);
  }

  public static void glColor3bv(byte[] v) {
    GlewArraysJNI.glColor3bv(v);
  }

  public static void glColor3dv(double[] v) {
    GlewArraysJNI.glColor3dv(v);
  }

  public static void glColor3fv(float[] v) {
    GlewArraysJNI.glColor3fv(v);
  }

  public static void glColor3iv(int[] v) {
    GlewArraysJNI.glColor3iv(v);
  }

  public static void glColor3sv(short[] v) {
    GlewArraysJNI.glColor3sv(v);
  }

  public static void glColor3ubv(short[] v) {
    GlewArraysJNI.glColor3ubv(v);
  }

  public static void glColor3uiv(long[] v) {
    GlewArraysJNI.glColor3uiv(v);
  }

  public static void glColor3usv(int[] v) {
    GlewArraysJNI.glColor3usv(v);
  }

  public static void glColor4bv(byte[] v) {
    GlewArraysJNI.glColor4bv(v);
  }

  public static void glColor4dv(double[] v) {
    GlewArraysJNI.glColor4dv(v);
  }

  public static void glColor4fv(float[] v) {
    GlewArraysJNI.glColor4fv(v);
  }

  public static void glColor4iv(int[] v) {
    GlewArraysJNI.glColor4iv(v);
  }

  public static void glColor4sv(short[] v) {
    GlewArraysJNI.glColor4sv(v);
  }

  public static void glColor4ubv(short[] v) {
    GlewArraysJNI.glColor4ubv(v);
  }

  public static void glColor4uiv(long[] v) {
    GlewArraysJNI.glColor4uiv(v);
  }

  public static void glColor4usv(int[] v) {
    GlewArraysJNI.glColor4usv(v);
  }

  public static void glTexCoord1dv(double[] v) {
    GlewArraysJNI.glTexCoord1dv(v);
  }

  public static void glTexCoord1fv(float[] v) {
    GlewArraysJNI.glTexCoord1fv(v);
  }

  public static void glTexCoord1iv(int[] v) {
    GlewArraysJNI.glTexCoord1iv(v);
  }

  public static void glTexCoord1sv(short[] v) {
    GlewArraysJNI.glTexCoord1sv(v);
  }

  public static void glTexCoord2dv(double[] v) {
    GlewArraysJNI.glTexCoord2dv(v);
  }

  public static void glTexCoord2fv(float[] v) {
    GlewArraysJNI.glTexCoord2fv(v);
  }

  public static void glTexCoord2iv(int[] v) {
    GlewArraysJNI.glTexCoord2iv(v);
  }

  public static void glTexCoord2sv(short[] v) {
    GlewArraysJNI.glTexCoord2sv(v);
  }

  public static void glTexCoord3dv(double[] v) {
    GlewArraysJNI.glTexCoord3dv(v);
  }

  public static void glTexCoord3fv(float[] v) {
    GlewArraysJNI.glTexCoord3fv(v);
  }

  public static void glTexCoord3iv(int[] v) {
    GlewArraysJNI.glTexCoord3iv(v);
  }

  public static void glTexCoord3sv(short[] v) {
    GlewArraysJNI.glTexCoord3sv(v);
  }

  public static void glTexCoord4dv(double[] v) {
    GlewArraysJNI.glTexCoord4dv(v);
  }

  public static void glTexCoord4fv(float[] v) {
    GlewArraysJNI.glTexCoord4fv(v);
  }

  public static void glTexCoord4iv(int[] v) {
    GlewArraysJNI.glTexCoord4iv(v);
  }

  public static void glTexCoord4sv(short[] v) {
    GlewArraysJNI.glTexCoord4sv(v);
  }

  public static void glRasterPos2dv(double[] v) {
    GlewArraysJNI.glRasterPos2dv(v);
  }

  public static void glRasterPos2fv(float[] v) {
    GlewArraysJNI.glRasterPos2fv(v);
  }

  public static void glRasterPos2iv(int[] v) {
    GlewArraysJNI.glRasterPos2iv(v);
  }

  public static void glRasterPos2sv(short[] v) {
    GlewArraysJNI.glRasterPos2sv(v);
  }

  public static void glRasterPos3dv(double[] v) {
    GlewArraysJNI.glRasterPos3dv(v);
  }

  public static void glRasterPos3fv(float[] v) {
    GlewArraysJNI.glRasterPos3fv(v);
  }

  public static void glRasterPos3iv(int[] v) {
    GlewArraysJNI.glRasterPos3iv(v);
  }

  public static void glRasterPos3sv(short[] v) {
    GlewArraysJNI.glRasterPos3sv(v);
  }

  public static void glRasterPos4dv(double[] v) {
    GlewArraysJNI.glRasterPos4dv(v);
  }

  public static void glRasterPos4fv(float[] v) {
    GlewArraysJNI.glRasterPos4fv(v);
  }

  public static void glRasterPos4iv(int[] v) {
    GlewArraysJNI.glRasterPos4iv(v);
  }

  public static void glRasterPos4sv(short[] v) {
    GlewArraysJNI.glRasterPos4sv(v);
  }

  public static void glRectdv(double[] v1, double[] v2) {
    GlewArraysJNI.glRectdv(v1, v2);
  }

  public static void glRectfv(float[] v1, float[] v2) {
    GlewArraysJNI.glRectfv(v1, v2);
  }

  public static void glRectiv(int[] v1, int[] v2) {
    GlewArraysJNI.glRectiv(v1, v2);
  }

  public static void glRectsv(short[] v1, short[] v2) {
    GlewArraysJNI.glRectsv(v1, v2);
  }

  public static void glLightfv(long light, long pname, float[] params) {
    GlewArraysJNI.glLightfv(light, pname, params);
  }

  public static void glLightiv(long light, long pname, int[] params) {
    GlewArraysJNI.glLightiv(light, pname, params);
  }

  public static void glGetLightfv(long light, long pname, float[] params) {
    GlewArraysJNI.glGetLightfv(light, pname, params);
  }

  public static void glGetLightiv(long light, long pname, int[] params) {
    GlewArraysJNI.glGetLightiv(light, pname, params);
  }

  public static void glLightModelfv(long pname, float[] params) {
    GlewArraysJNI.glLightModelfv(pname, params);
  }

  public static void glLightModeliv(long pname, int[] params) {
    GlewArraysJNI.glLightModeliv(pname, params);
  }

  public static void glMaterialfv(long face, long pname, float[] params) {
    GlewArraysJNI.glMaterialfv(face, pname, params);
  }

  public static void glMaterialiv(long face, long pname, int[] params) {
    GlewArraysJNI.glMaterialiv(face, pname, params);
  }

  public static void glGetMaterialfv(long face, long pname, float[] params) {
    GlewArraysJNI.glGetMaterialfv(face, pname, params);
  }

  public static void glGetMaterialiv(long face, long pname, int[] params) {
    GlewArraysJNI.glGetMaterialiv(face, pname, params);
  }

  public static void glPixelMapfv(long map, int mapsize, float[] values) {
    GlewArraysJNI.glPixelMapfv(map, mapsize, values);
  }

  public static void glPixelMapuiv(long map, int mapsize, long[] values) {
    GlewArraysJNI.glPixelMapuiv(map, mapsize, values);
  }

  public static void glPixelMapusv(long map, int mapsize, int[] values) {
    GlewArraysJNI.glPixelMapusv(map, mapsize, values);
  }

  public static void glGetPixelMapfv(long map, float[] values) {
    GlewArraysJNI.glGetPixelMapfv(map, values);
  }

  public static void glGetPixelMapuiv(long map, long[] values) {
    GlewArraysJNI.glGetPixelMapuiv(map, values);
  }

  public static void glGetPixelMapusv(long map, int[] values) {
    GlewArraysJNI.glGetPixelMapusv(map, values);
  }

  public static void glBitmap(int width, int height, float xorig, float yorig, float xmove, float ymove, short[] bitmap) {
    GlewArraysJNI.glBitmap(width, height, xorig, yorig, xmove, ymove, bitmap);
  }

  public static void glTexGendv(long coord, long pname, double[] params) {
    GlewArraysJNI.glTexGendv(coord, pname, params);
  }

  public static void glTexGenfv(long coord, long pname, float[] params) {
    GlewArraysJNI.glTexGenfv(coord, pname, params);
  }

  public static void glTexGeniv(long coord, long pname, int[] params) {
    GlewArraysJNI.glTexGeniv(coord, pname, params);
  }

  public static void glGetTexGendv(long coord, long pname, double[] params) {
    GlewArraysJNI.glGetTexGendv(coord, pname, params);
  }

  public static void glGetTexGenfv(long coord, long pname, float[] params) {
    GlewArraysJNI.glGetTexGenfv(coord, pname, params);
  }

  public static void glGetTexGeniv(long coord, long pname, int[] params) {
    GlewArraysJNI.glGetTexGeniv(coord, pname, params);
  }

  public static void glTexEnvfv(long target, long pname, float[] params) {
    GlewArraysJNI.glTexEnvfv(target, pname, params);
  }

  public static void glTexEnviv(long target, long pname, int[] params) {
    GlewArraysJNI.glTexEnviv(target, pname, params);
  }

  public static void glGetTexEnvfv(long target, long pname, float[] params) {
    GlewArraysJNI.glGetTexEnvfv(target, pname, params);
  }

  public static void glGetTexEnviv(long target, long pname, int[] params) {
    GlewArraysJNI.glGetTexEnviv(target, pname, params);
  }

  public static void glTexParameterfv(long target, long pname, float[] params) {
    GlewArraysJNI.glTexParameterfv(target, pname, params);
  }

  public static void glTexParameteriv(long target, long pname, int[] params) {
    GlewArraysJNI.glTexParameteriv(target, pname, params);
  }

  public static void glGetTexParameterfv(long target, long pname, float[] params) {
    GlewArraysJNI.glGetTexParameterfv(target, pname, params);
  }

  public static void glGetTexParameteriv(long target, long pname, int[] params) {
    GlewArraysJNI.glGetTexParameteriv(target, pname, params);
  }

  public static void glGetTexLevelParameterfv(long target, int level, long pname, float[] params) {
    GlewArraysJNI.glGetTexLevelParameterfv(target, level, pname, params);
  }

  public static void glGetTexLevelParameteriv(long target, int level, long pname, int[] params) {
    GlewArraysJNI.glGetTexLevelParameteriv(target, level, pname, params);
  }

  public static void glGenTextures(int n, long[] textures) {
    GlewArraysJNI.glGenTextures(n, textures);
  }

  public static void glDeleteTextures(int n, long[] textures) {
    GlewArraysJNI.glDeleteTextures(n, textures);
  }

  public static void glPrioritizeTextures(int n, long[] textures, float[] priorities) {
    GlewArraysJNI.glPrioritizeTextures(n, textures, priorities);
  }

  public static short glAreTexturesResident(int n, long[] textures, short[] residences) {
    return GlewArraysJNI.glAreTexturesResident(n, textures, residences);
  }

  public static void glMap1d(long target, double u1, double u2, int stride, int order, double[] points) {
    GlewArraysJNI.glMap1d(target, u1, u2, stride, order, points);
  }

  public static void glMap1f(long target, float u1, float u2, int stride, int order, float[] points) {
    GlewArraysJNI.glMap1f(target, u1, u2, stride, order, points);
  }

  public static void glMap2d(long target, double u1, double u2, int ustride, int uorder, double v1, double v2, int vstride, int vorder, double[] points) {
    GlewArraysJNI.glMap2d(target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points);
  }

  public static void glMap2f(long target, float u1, float u2, int ustride, int uorder, float v1, float v2, int vstride, int vorder, float[] points) {
    GlewArraysJNI.glMap2f(target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points);
  }

  public static void glGetMapdv(long target, long query, double[] v) {
    GlewArraysJNI.glGetMapdv(target, query, v);
  }

  public static void glGetMapfv(long target, long query, float[] v) {
    GlewArraysJNI.glGetMapfv(target, query, v);
  }

  public static void glGetMapiv(long target, long query, int[] v) {
    GlewArraysJNI.glGetMapiv(target, query, v);
  }

  public static void glEvalCoord1dv(double[] u) {
    GlewArraysJNI.glEvalCoord1dv(u);
  }

  public static void glEvalCoord1fv(float[] u) {
    GlewArraysJNI.glEvalCoord1fv(u);
  }

  public static void glEvalCoord2dv(double[] u) {
    GlewArraysJNI.glEvalCoord2dv(u);
  }

  public static void glEvalCoord2fv(float[] u) {
    GlewArraysJNI.glEvalCoord2fv(u);
  }

  public static void glFogfv(long pname, float[] params) {
    GlewArraysJNI.glFogfv(pname, params);
  }

  public static void glFogiv(long pname, int[] params) {
    GlewArraysJNI.glFogiv(pname, params);
  }

  public static void glFeedbackBuffer(int size, long type, float[] buffer) {
    GlewArraysJNI.glFeedbackBuffer(size, type, buffer);
  }

  public static void glSelectBuffer(int size, long[] buffer) {
    GlewArraysJNI.glSelectBuffer(size, buffer);
  }

}
