/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.22
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gljava.opengl.glu;

public class GLUquadric {
  private long swigCPtr;

  public GLUquadric(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  public GLUquadric() {
    swigCPtr = 0;
  }

  public static long getCPtr(GLUquadric obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

