/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.22
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


  #include "GL/glew.h"


#if defined(SWIG_NOINCLUDE) || defined(SWIG_NOARRAYS)


int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input);
void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input);
jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz);


int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input);
void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input);
jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz);


int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input);
void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input);
jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz);


int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input);
void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input);
jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz);


int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input);
void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input);
jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz);


int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input);
void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz);


int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input);
void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input);
jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz);


int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input);
void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz);


int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input);
void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz);


int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input);
void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input);
jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz);


int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input);
void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input);
jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz);


#else


/* signed char[] support */
int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetByteArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (signed char*) calloc(sz, sizeof(signed char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (signed char)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jbyte)carr[i];
  (*jenv)->ReleaseByteArrayElements(jenv, input, jarr, 0);
}

jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = (*jenv)->NewByteArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetByteArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  (*jenv)->ReleaseByteArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned char[] support */
int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned char*) calloc(sz, sizeof(unsigned char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned char)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* short[] support */
int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (short*) calloc(sz, sizeof(short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (short)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned short[] support */
int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned short*) calloc(sz, sizeof(unsigned short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned short)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* int[] support */
int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (int*) calloc(sz, sizeof(int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (int)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned int[] support */
int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned int*) calloc(sz, sizeof(unsigned int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned int)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* long[] support */
int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (long*) calloc(sz, sizeof(long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (long)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned long[] support */
int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned long*) calloc(sz, sizeof(unsigned long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned long)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* jlong[] support */
int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (jlong*) calloc(sz, sizeof(jlong)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (jlong)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* float[] support */
int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetFloatArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (float*) calloc(sz, sizeof(float)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (float)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jfloat)carr[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, input, jarr, 0);
}

jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz) {
  jfloat *arr;
  int i;
  jfloatArray jresult = (*jenv)->NewFloatArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetFloatArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jfloat)result[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* double[] support */
int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetDoubleArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (double*) calloc(sz, sizeof(double)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (double)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jdouble)carr[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, input, jarr, 0);
}

jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz) {
  jdouble *arr;
  int i;
  jdoubleArray jresult = (*jenv)->NewDoubleArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetDoubleArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jdouble)result[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


#endif


#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glPolygonStipple(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLubyte *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glPolygonStipple((GLubyte const (*))arg1);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetPolygonStipple(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLubyte *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glGetPolygonStipple(arg1);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glEdgeFlagv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLboolean *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glEdgeFlagv((GLboolean const (*))arg1);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glClipPlane(JNIEnv *jenv, jclass jcls, jlong jarg1, jdoubleArray jarg2) {
    GLenum arg1 ;
    GLdouble *arg2 ;
    jdouble *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr2, &arg2, jarg2)) return ; 
    glClipPlane(arg1,(GLdouble const (*))arg2);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetClipPlane(JNIEnv *jenv, jclass jcls, jlong jarg1, jdoubleArray jarg2) {
    GLenum arg1 ;
    GLdouble *arg2 ;
    jdouble *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetClipPlane(arg1,arg2);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetBooleanv(JNIEnv *jenv, jclass jcls, jlong jarg1, jshortArray jarg2) {
    GLenum arg1 ;
    GLboolean *arg2 ;
    jshort *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInUchar(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetBooleanv(arg1,arg2);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetDoublev(JNIEnv *jenv, jclass jcls, jlong jarg1, jdoubleArray jarg2) {
    GLenum arg1 ;
    GLdouble *arg2 ;
    jdouble *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetDoublev(arg1,arg2);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetFloatv(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloatArray jarg2) {
    GLenum arg1 ;
    GLfloat *arg2 ;
    jfloat *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetFloatv(arg1,arg2);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetIntegerv(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
    GLenum arg1 ;
    GLint *arg2 ;
    jint *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetIntegerv(arg1,arg2);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glLoadMatrixd(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glLoadMatrixd((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glLoadMatrixf(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glLoadMatrixf((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMultMatrixd(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glMultMatrixd((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMultMatrixf(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glMultMatrixf((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex2dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex2dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex2fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex2fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex2iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex2iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex2sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex2sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex3dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex3dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex3fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex3fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex3iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex3iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex3sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex3sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex4dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex4dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex4fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex4fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex4iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex4iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glVertex4sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glVertex4sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glNormal3bv(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
    GLbyte *arg1 ;
    jbyte *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInSchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glNormal3bv((GLbyte const (*))arg1);
    
    SWIG_JavaArrayArgoutSchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glNormal3dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glNormal3dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glNormal3fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glNormal3fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glNormal3iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glNormal3iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glNormal3sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glNormal3sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glIndexdv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glIndexdv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glIndexfv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glIndexfv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glIndexiv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glIndexiv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glIndexsv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glIndexsv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glIndexubv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLubyte *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glIndexubv((GLubyte const (*))arg1);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3bv(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
    GLbyte *arg1 ;
    jbyte *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInSchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3bv((GLbyte const (*))arg1);
    
    SWIG_JavaArrayArgoutSchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3ubv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLubyte *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3ubv((GLubyte const (*))arg1);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3uiv(JNIEnv *jenv, jclass jcls, jlongArray jarg1) {
    GLuint *arg1 ;
    jlong *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUint(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3uiv((GLuint const (*))arg1);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor3usv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLushort *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUshort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor3usv((GLushort const (*))arg1);
    
    SWIG_JavaArrayArgoutUshort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4bv(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
    GLbyte *arg1 ;
    jbyte *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInSchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4bv((GLbyte const (*))arg1);
    
    SWIG_JavaArrayArgoutSchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4ubv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLubyte *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUchar(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4ubv((GLubyte const (*))arg1);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4uiv(JNIEnv *jenv, jclass jcls, jlongArray jarg1) {
    GLuint *arg1 ;
    jlong *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUint(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4uiv((GLuint const (*))arg1);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glColor4usv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLushort *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInUshort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glColor4usv((GLushort const (*))arg1);
    
    SWIG_JavaArrayArgoutUshort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord1dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord1dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord1fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord1fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord1iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord1iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord1sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord1sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord2dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord2dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord2fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord2fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord2iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord2iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord2sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord2sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord3dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord3dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord3fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord3fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord3iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord3iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord3sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord3sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord4dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord4dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord4fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord4fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord4iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord4iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexCoord4sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glTexCoord4sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos2dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos2dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos2fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos2fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos2iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos2iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos2sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos2sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos3dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos3dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos3fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos3fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos3iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos3iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos3sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos3sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos4dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos4dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos4fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos4fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos4iv(JNIEnv *jenv, jclass jcls, jintArray jarg1) {
    GLint *arg1 ;
    jint *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos4iv((GLint const (*))arg1);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRasterPos4sv(JNIEnv *jenv, jclass jcls, jshortArray jarg1) {
    GLshort *arg1 ;
    jshort *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    glRasterPos4sv((GLshort const (*))arg1);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRectdv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1, jdoubleArray jarg2) {
    GLdouble *arg1 ;
    GLdouble *arg2 ;
    jdouble *jarr1 ;
    jdouble *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr2, &arg2, jarg2)) return ; 
    glRectdv((GLdouble const (*))arg1,(GLdouble const (*))arg2);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    SWIG_JavaArrayArgoutDouble(jenv, jarr2, arg2, jarg2); 
    free(arg1); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRectfv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1, jfloatArray jarg2) {
    GLfloat *arg1 ;
    GLfloat *arg2 ;
    jfloat *jarr1 ;
    jfloat *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr2, &arg2, jarg2)) return ; 
    glRectfv((GLfloat const (*))arg1,(GLfloat const (*))arg2);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    SWIG_JavaArrayArgoutFloat(jenv, jarr2, arg2, jarg2); 
    free(arg1); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRectiv(JNIEnv *jenv, jclass jcls, jintArray jarg1, jintArray jarg2) {
    GLint *arg1 ;
    GLint *arg2 ;
    jint *jarr1 ;
    jint *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInInt(jenv, &jarr1, &arg1, jarg1)) return ; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr2, &arg2, jarg2)) return ; 
    glRectiv((GLint const (*))arg1,(GLint const (*))arg2);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr1, arg1, jarg1); 
    SWIG_JavaArrayArgoutInt(jenv, jarr2, arg2, jarg2); 
    free(arg1); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glRectsv(JNIEnv *jenv, jclass jcls, jshortArray jarg1, jshortArray jarg2) {
    GLshort *arg1 ;
    GLshort *arg2 ;
    jshort *jarr1 ;
    jshort *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInShort(jenv, &jarr1, &arg1, jarg1)) return ; 
    if (!SWIG_JavaArrayInShort(jenv, &jarr2, &arg2, jarg2)) return ; 
    glRectsv((GLshort const (*))arg1,(GLshort const (*))arg2);
    
    SWIG_JavaArrayArgoutShort(jenv, jarr1, arg1, jarg1); 
    SWIG_JavaArrayArgoutShort(jenv, jarr2, arg2, jarg2); 
    free(arg1); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glLightfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glLightfv(arg1,arg2,(GLfloat const (*))arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glLightiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glLightiv(arg1,arg2,(GLint const (*))arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetLightfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetLightfv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetLightiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetLightiv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glLightModelfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloatArray jarg2) {
    GLenum arg1 ;
    GLfloat *arg2 ;
    jfloat *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr2, &arg2, jarg2)) return ; 
    glLightModelfv(arg1,(GLfloat const (*))arg2);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glLightModeliv(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
    GLenum arg1 ;
    GLint *arg2 ;
    jint *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr2, &arg2, jarg2)) return ; 
    glLightModeliv(arg1,(GLint const (*))arg2);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMaterialfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glMaterialfv(arg1,arg2,(GLfloat const (*))arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMaterialiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glMaterialiv(arg1,arg2,(GLint const (*))arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetMaterialfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetMaterialfv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetMaterialiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetMaterialiv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glPixelMapfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLint arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLint)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glPixelMapfv(arg1,arg2,(GLfloat const (*))arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glPixelMapuiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlongArray jarg3) {
    GLenum arg1 ;
    GLint arg2 ;
    GLuint *arg3 ;
    jlong *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLint)jarg2; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr3, &arg3, jarg3)) return ; 
    glPixelMapuiv(arg1,arg2,(GLuint const (*))arg3);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glPixelMapusv(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLint arg2 ;
    GLushort *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLint)jarg2; 
    if (!SWIG_JavaArrayInUshort(jenv, &jarr3, &arg3, jarg3)) return ; 
    glPixelMapusv(arg1,arg2,(GLushort const (*))arg3);
    
    SWIG_JavaArrayArgoutUshort(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetPixelMapfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloatArray jarg2) {
    GLenum arg1 ;
    GLfloat *arg2 ;
    jfloat *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetPixelMapfv(arg1,arg2);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetPixelMapuiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlongArray jarg2) {
    GLenum arg1 ;
    GLuint *arg2 ;
    jlong *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetPixelMapuiv(arg1,arg2);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetPixelMapusv(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
    GLenum arg1 ;
    GLushort *arg2 ;
    jint *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInUshort(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGetPixelMapusv(arg1,arg2);
    
    SWIG_JavaArrayArgoutUshort(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glBitmap(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5, jfloat jarg6, jshortArray jarg7) {
    GLsizei arg1 ;
    GLsizei arg2 ;
    GLfloat arg3 ;
    GLfloat arg4 ;
    GLfloat arg5 ;
    GLfloat arg6 ;
    GLubyte *arg7 ;
    jshort *jarr7 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    arg2 = (GLsizei)jarg2; 
    arg3 = (GLfloat)jarg3; 
    arg4 = (GLfloat)jarg4; 
    arg5 = (GLfloat)jarg5; 
    arg6 = (GLfloat)jarg6; 
    if (!SWIG_JavaArrayInUchar(jenv, &jarr7, &arg7, jarg7)) return ; 
    glBitmap(arg1,arg2,arg3,arg4,arg5,arg6,(GLubyte const (*))arg7);
    
    SWIG_JavaArrayArgoutUchar(jenv, jarr7, arg7, jarg7); 
    free(arg7); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexGendv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jdoubleArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLdouble *arg3 ;
    jdouble *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexGendv(arg1,arg2,(GLdouble const (*))arg3);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexGenfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexGenfv(arg1,arg2,(GLfloat const (*))arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexGeniv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexGeniv(arg1,arg2,(GLint const (*))arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexGendv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jdoubleArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLdouble *arg3 ;
    jdouble *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexGendv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexGenfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexGenfv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexGeniv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexGeniv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexEnvfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexEnvfv(arg1,arg2,(GLfloat const (*))arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexEnviv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexEnviv(arg1,arg2,(GLint const (*))arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexEnvfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexEnvfv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexEnviv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexEnviv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexParameterfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexParameterfv(arg1,arg2,(GLfloat const (*))arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glTexParameteriv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glTexParameteriv(arg1,arg2,(GLint const (*))arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexParameterfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexParameterfv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexParameteriv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetTexParameteriv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexLevelParameterfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jfloatArray jarg4) {
    GLenum arg1 ;
    GLint arg2 ;
    GLenum arg3 ;
    GLfloat *arg4 ;
    jfloat *jarr4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLint)jarg2; 
    arg3 = (GLenum)jarg3; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr4, &arg4, jarg4)) return ; 
    glGetTexLevelParameterfv(arg1,arg2,arg3,arg4);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr4, arg4, jarg4); 
    free(arg4); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetTexLevelParameteriv(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jintArray jarg4) {
    GLenum arg1 ;
    GLint arg2 ;
    GLenum arg3 ;
    GLint *arg4 ;
    jint *jarr4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLint)jarg2; 
    arg3 = (GLenum)jarg3; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr4, &arg4, jarg4)) return ; 
    glGetTexLevelParameteriv(arg1,arg2,arg3,arg4);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr4, arg4, jarg4); 
    free(arg4); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGenTextures(JNIEnv *jenv, jclass jcls, jint jarg1, jlongArray jarg2) {
    GLsizei arg1 ;
    GLuint *arg2 ;
    jlong *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr2, &arg2, jarg2)) return ; 
    glGenTextures(arg1,arg2);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glDeleteTextures(JNIEnv *jenv, jclass jcls, jint jarg1, jlongArray jarg2) {
    GLsizei arg1 ;
    GLuint *arg2 ;
    jlong *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr2, &arg2, jarg2)) return ; 
    glDeleteTextures(arg1,(GLuint const (*))arg2);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glPrioritizeTextures(JNIEnv *jenv, jclass jcls, jint jarg1, jlongArray jarg2, jfloatArray jarg3) {
    GLsizei arg1 ;
    GLuint *arg2 ;
    GLclampf *arg3 ;
    jlong *jarr2 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr2, &arg2, jarg2)) return ; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glPrioritizeTextures(arg1,(GLuint const (*))arg2,(GLclampf const (*))arg3);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr2, arg2, jarg2); 
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg2); 
    free(arg3); 
}


JNIEXPORT jshort JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glAreTexturesResident(JNIEnv *jenv, jclass jcls, jint jarg1, jlongArray jarg2, jshortArray jarg3) {
    jshort jresult = 0 ;
    GLsizei arg1 ;
    GLuint *arg2 ;
    GLboolean *arg3 ;
    GLboolean result;
    jlong *jarr2 ;
    jshort *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr2, &arg2, jarg2)) return 0; 
    if (!SWIG_JavaArrayInUchar(jenv, &jarr3, &arg3, jarg3)) return 0; 
    result = (GLboolean)glAreTexturesResident(arg1,(GLuint const (*))arg2,arg3);
    
    jresult = (jshort)result; 
    SWIG_JavaArrayArgoutUint(jenv, jarr2, arg2, jarg2); 
    SWIG_JavaArrayArgoutUchar(jenv, jarr3, arg3, jarg3); 
    free(arg2); 
    free(arg3); 
    return jresult;
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMap1d(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jdouble jarg3, jint jarg4, jint jarg5, jdoubleArray jarg6) {
    GLenum arg1 ;
    GLdouble arg2 ;
    GLdouble arg3 ;
    GLint arg4 ;
    GLint arg5 ;
    GLdouble *arg6 ;
    jdouble *jarr6 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLdouble)jarg2; 
    arg3 = (GLdouble)jarg3; 
    arg4 = (GLint)jarg4; 
    arg5 = (GLint)jarg5; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr6, &arg6, jarg6)) return ; 
    glMap1d(arg1,arg2,arg3,arg4,arg5,(GLdouble const (*))arg6);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr6, arg6, jarg6); 
    free(arg6); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMap1f(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2, jfloat jarg3, jint jarg4, jint jarg5, jfloatArray jarg6) {
    GLenum arg1 ;
    GLfloat arg2 ;
    GLfloat arg3 ;
    GLint arg4 ;
    GLint arg5 ;
    GLfloat *arg6 ;
    jfloat *jarr6 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLfloat)jarg2; 
    arg3 = (GLfloat)jarg3; 
    arg4 = (GLint)jarg4; 
    arg5 = (GLint)jarg5; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr6, &arg6, jarg6)) return ; 
    glMap1f(arg1,arg2,arg3,arg4,arg5,(GLfloat const (*))arg6);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr6, arg6, jarg6); 
    free(arg6); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMap2d(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jdouble jarg3, jint jarg4, jint jarg5, jdouble jarg6, jdouble jarg7, jint jarg8, jint jarg9, jdoubleArray jarg10) {
    GLenum arg1 ;
    GLdouble arg2 ;
    GLdouble arg3 ;
    GLint arg4 ;
    GLint arg5 ;
    GLdouble arg6 ;
    GLdouble arg7 ;
    GLint arg8 ;
    GLint arg9 ;
    GLdouble *arg10 ;
    jdouble *jarr10 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLdouble)jarg2; 
    arg3 = (GLdouble)jarg3; 
    arg4 = (GLint)jarg4; 
    arg5 = (GLint)jarg5; 
    arg6 = (GLdouble)jarg6; 
    arg7 = (GLdouble)jarg7; 
    arg8 = (GLint)jarg8; 
    arg9 = (GLint)jarg9; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr10, &arg10, jarg10)) return ; 
    glMap2d(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,(GLdouble const (*))arg10);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr10, arg10, jarg10); 
    free(arg10); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glMap2f(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2, jfloat jarg3, jint jarg4, jint jarg5, jfloat jarg6, jfloat jarg7, jint jarg8, jint jarg9, jfloatArray jarg10) {
    GLenum arg1 ;
    GLfloat arg2 ;
    GLfloat arg3 ;
    GLint arg4 ;
    GLint arg5 ;
    GLfloat arg6 ;
    GLfloat arg7 ;
    GLint arg8 ;
    GLint arg9 ;
    GLfloat *arg10 ;
    jfloat *jarr10 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLfloat)jarg2; 
    arg3 = (GLfloat)jarg3; 
    arg4 = (GLint)jarg4; 
    arg5 = (GLint)jarg5; 
    arg6 = (GLfloat)jarg6; 
    arg7 = (GLfloat)jarg7; 
    arg8 = (GLint)jarg8; 
    arg9 = (GLint)jarg9; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr10, &arg10, jarg10)) return ; 
    glMap2f(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,(GLfloat const (*))arg10);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr10, arg10, jarg10); 
    free(arg10); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetMapdv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jdoubleArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLdouble *arg3 ;
    jdouble *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInDouble(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetMapdv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetMapfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jfloatArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetMapfv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glGetMapiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jintArray jarg3) {
    GLenum arg1 ;
    GLenum arg2 ;
    GLint *arg3 ;
    jint *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr3, &arg3, jarg3)) return ; 
    glGetMapiv(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glEvalCoord1dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glEvalCoord1dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glEvalCoord1fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glEvalCoord1fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glEvalCoord2dv(JNIEnv *jenv, jclass jcls, jdoubleArray jarg1) {
    GLdouble *arg1 ;
    jdouble *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInDouble(jenv, &jarr1, &arg1, jarg1)) return ; 
    glEvalCoord2dv((GLdouble const (*))arg1);
    
    SWIG_JavaArrayArgoutDouble(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glEvalCoord2fv(JNIEnv *jenv, jclass jcls, jfloatArray jarg1) {
    GLfloat *arg1 ;
    jfloat *jarr1 ;
    
    (void)jenv;
    (void)jcls;
    if (!SWIG_JavaArrayInFloat(jenv, &jarr1, &arg1, jarg1)) return ; 
    glEvalCoord2fv((GLfloat const (*))arg1);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr1, arg1, jarg1); 
    free(arg1); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glFogfv(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloatArray jarg2) {
    GLenum arg1 ;
    GLfloat *arg2 ;
    jfloat *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr2, &arg2, jarg2)) return ; 
    glFogfv(arg1,(GLfloat const (*))arg2);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glFogiv(JNIEnv *jenv, jclass jcls, jlong jarg1, jintArray jarg2) {
    GLenum arg1 ;
    GLint *arg2 ;
    jint *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLenum)jarg1; 
    if (!SWIG_JavaArrayInInt(jenv, &jarr2, &arg2, jarg2)) return ; 
    glFogiv(arg1,(GLint const (*))arg2);
    
    SWIG_JavaArrayArgoutInt(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glFeedbackBuffer(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jfloatArray jarg3) {
    GLsizei arg1 ;
    GLenum arg2 ;
    GLfloat *arg3 ;
    jfloat *jarr3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    arg2 = (GLenum)jarg2; 
    if (!SWIG_JavaArrayInFloat(jenv, &jarr3, &arg3, jarg3)) return ; 
    glFeedbackBuffer(arg1,arg2,arg3);
    
    SWIG_JavaArrayArgoutFloat(jenv, jarr3, arg3, jarg3); 
    free(arg3); 
}


JNIEXPORT void JNICALL Java_org_gljava_opengl_x_swig_GlewArraysJNI_glSelectBuffer(JNIEnv *jenv, jclass jcls, jint jarg1, jlongArray jarg2) {
    GLsizei arg1 ;
    GLuint *arg2 ;
    jlong *jarr2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (GLsizei)jarg1; 
    if (!SWIG_JavaArrayInUint(jenv, &jarr2, &arg2, jarg2)) return ; 
    glSelectBuffer(arg1,arg2);
    
    SWIG_JavaArrayArgoutUint(jenv, jarr2, arg2, jarg2); 
    free(arg2); 
}


#ifdef __cplusplus
}
#endif

